name: Plugin asset/readme update
on:
  push:
    branches:
    - main
    paths:
    - '.wordpress-org/**'
    - 'readme.txt'
jobs:
  main:
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        ASSETS_DIR: .wordpress-org/assets
        README_NAME: .wordpress-org/readme.txt
        SLUG: admin-user-delete-with-contents-disabled
